language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="46bae9bf-ba1b-4932-86ed-88bb07e72de9"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - akulmmm@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
