# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - akulmmm@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

    env:
      global:
        - CODECOV_TOKEN="82738608-b08f-4ade-9319-53cb7d712e04"

