language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="Jx0423-NMAN3ajgyKmEsTQ"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - akulmmm@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
