language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="b47eb3d5-b4fc-4ff1-8ea2-fc30224a6d5c"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - akulmmm@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
