language: java

jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="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"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - akulmmm@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
